quote = [
          "Some lose all mind and become soul, insane. Some lose all soul and become mind, intellectual. Some lose both and become accepted",
          "Do you hate people? I don't hate them...I just feel better when they're not around.",
          "There is a place in the heart that will never be filled... a space, and even during the best moments and the greatest times, we will know it, we will know it more than ever, there is a place in the heart that will never be fille and we will wait and wait in that space.",
          "Some people never go crazy. What truly horrible lives they must lead.",
          "What matters most is how well you walk through the fire.",
          "Sometimes you climb out of bed in the morning and you think, I'm not going to make it, but you laugh inside - remembering all the times you've felt that way.",
          "We're all going to die, all of us, what a circus! That alone should make us love each other but it doesn't. We are terrorized and flattened by trivialities, we are eaten up by nothing.",
          "I wanted the whole world or nothing.",
          "An intellectual says a simple thing in a hard way. An artist says a hard thing in a simple way.",
          "If you're losing your soul and you know it, then you've still got a soul left to lose",
          "Find what you love and let it kill you.",
          "Those who escape hell however, never talk about it and nothing much bothers them after that.",
          "Of course it's possible to love a human being if you don't know them too well.",
          "Sex is kicking death in the ass while singing.",
          "Sometimes you just have to pee in the sink.",
          "I often carry things to read so that I will not have to look at the people.",
          "It wasn't my day. My week. My month. My year. My life. God damn it",
          "I want so much that is not here and do not know where to go.",
          "You son of a bitch, she said, I am trying to build a meaningful relationship. You can't build it with a hammer, he said.",
          "It was like the beginning of life and laughter. It was the real meaning of the sun",
          "The trouble with a mask is it never changes",
          "In the morning it was morning and I was still alive.",
          "We are here to laugh at the odds and live our lives so well that Death will tremble to take us.",
          "The fuckers. There, I feel better. God-damned human race. There, I feel better.",
          "The tigers have found me and I do not care.",
          "She's mad but she's magic. There's no lie in her fire.",
          "I wish to weep but sorrow is stupid. I wish to believe but belief is a graveyard.",
          "Nothing can save you except writing. It keeps the walls from failing.",
          "People run from rain but sit in bathtubs full of water.",
          "Any asshole can chase a skirt, art takes discipline.",
          "I wasn't a misanthrope and I wasn't a misogynist but I liked being alone. It felt good to sit alone in a small space and smoke and drink. I had always been good company for myself.",
          "He asked, 'What makes a man a writer?' 'Well,' I said, 'it's simple. You either get it down on paper, or jump off a bridge.'",
          "To fight for each minute is to fight for what is possible within yourself, so that your life and your death will not be like theirs.",
          "Beauty is nothing, beauty won't stay. You don't know how lucky you are to be ugly, because if people like you, you know it's for something else.",
          "One can never be sure whether it's good poetry or bad acid",
          "Nobody can save you but yourself and you're worth saving. It's a war not easily won but if anything is worth winning then this is it.",
          "Nothing is worse than to finish a good shit, then reach over and find the toilet paper container empty. Even the most horrible human being on earth deserves to wipe his ass.",
          "In my next life I want to be a cat. To sleep 20 hours a day and wait to be fed. To sit around licking my ass.",
          "It's better to do a dull thing with style than a dangerous thing without it.",
          "It was better for me when I could imagine greatness in others, even if it wasn't always there.",
          "The more crap you believe, the better off you are.",
          "I didn't have any friends at school, didn't want any. I felt better being alone. I sat on a bench and watched the others play and they looked foolish to me.",
          "I don't know about other people, but when I wake up in the morning and put my shoes on, I think, Jesus Christ, now what?",
          "It was a joy! Words weren't dull, words were things that could make your mind hum. If you read them and let yourself feel the magic, you could live without pain, with hope, no matter what happened to you.",
          "Some people like what you do, some people hate what you do, but most people simply don't give a damn.",
          "Goodness can be found sometimes in the middle of hell."
          ]

author = "~ Charles Bukowski"
