Alcoholdict = {'supermarkt': "Spar", 'wat': "Prinsdom van Oranje wijn", 'korting': "1 euro en 50 cent" , 'hoeveel': "0,75 liter", 'normaal': "3 euro en 99 cent", 'deze week': "2 euro en 49 cent"}
Alcoholdict1 = {'supermarkt': "Hema", 'wat': "Cava Copa sabia brut", 'korting': "3 euro" , 'hoeveel': "2 flessen a 75 cl", 'normaal': "15 euro", 'deze week': "12 euro"}
Alcoholdict2 = {'supermarkt': "Hema", 'wat': "Cava Copa sabia rosado", 'korting': "3 euro" , 'hoeveel': "2 flessen a 75 cl", 'normaal': "15 euro", 'deze week': "12 euro"}
Alcoholdict3 = {'supermarkt': "Hema", 'wat': "Clairette de die wijn", 'korting': "3 euro" , 'hoeveel': "2 flessen a 75 cl", 'normaal': "15 euro", 'deze week': "cent"}
Alcoholdict4 = {'supermarkt': "Jan Linders", 'wat': "Bavaria of Brand bier", 'korting': "2+1 gratis" , 'hoeveel': "krat 12x30 cl", 'normaal': "15 euro en 65 cent", 'deze week': "11 euro en 10 cent"}
Alcoholdict5 = {'supermarkt': "Jan Linders", 'wat': "Freixenet cava", 'korting': "2 euro" , 'hoeveel': "fles 750 ml", 'normaal': "9 euro en 99 cent", 'deze week': "7 euro en 99 cent"}
Alcoholdict6 = {'supermarkt': "Jan Linders", 'wat': "Martini", 'korting': "1 euro" , 'hoeveel': "fles 750 ml", 'normaal': "7 euro en 99 cent", 'deze week': "6 euro en 99 cent"}
Alcoholdict7 = {'supermarkt': "Jan Linders", 'wat': "Gran espanoso cava", 'korting': "70 cent" , 'hoeveel': "fles 750 ml", 'normaal': "5 euro en 79 cent", 'deze week': "4 euro en 99 cent"}
Alcoholdict8 = {'supermarkt': "Jan Linders", 'wat': "Montpervier champagne", 'korting': "4 euro en 30 cent" , 'hoeveel': "fles 750 ml", 'normaal': "19 euro en 99 cent", 'deze week': "14 euro en 69 cent"}
Alcoholdict9 = {'supermarkt': "Jan Linders", 'wat': "Brut Dargent rose", 'korting': "2 euro" , 'hoeveel': "fles 750 ml", 'normaal': "9 euro en 99 cent", 'deze week': "7 euro en 99 cent"}
Alcoholdict10 = {'supermarkt': "Jan Linders", 'wat': "Don Luciano charmat moscato sparkling", 'korting': "3 euro en 99 cent" , 'hoeveel': "fles 750 ml", 'normaal': "7 euro en 98 cent", 'deze week': "3 euro en 99 cent"}
Alcoholdict11 = {'supermarkt': "Jan Linders", 'wat': "Tiresia Prosecco of raboso", 'korting': "1 euro en 50 cent" , 'hoeveel': "fles 750 ml", 'normaal': "4 euro en 59 cent", 'deze week': "2 euro en 99 cent"}
Alcoholdict12 = {'supermarkt': "Jan Linders", 'wat': "Bavaria Radler", 'korting': "1 euro en 6 cent" , 'hoeveel': "tray 6x30 cl", 'normaal': "3 euro en 35 cent", 'deze week': "2 euro en 49 cent"}
Alcoholdict13 = {'supermarkt': "Jan Linders", 'wat': "Desperados", 'korting': "90 cent" , 'hoeveel': "tray 3x33 cl", 'normaal': "4 euro en 89 cent", 'deze week': "3 euro en 99 cent"}
Alcoholdict14 = {'supermarkt': "Albert Heijn", 'wat': "Jacob's Creek sparkling brut of rose", 'korting': "3 euro" , 'hoeveel': "fles 0.75 liter", 'normaal': "11 euro en 99 cent", 'deze week': "8 euro en 99 cent"}
Alcoholdict15 = {'supermarkt': "Albert Heijn", 'wat': "Lindeman's Bin sparkling brut of rose", 'korting': "2 euro en 50 cent" , 'hoeveel': "fles 0.75 liter", 'normaal': "9 euro en 99 cent", 'deze week': "7 euro en 49 cent"}
Alcoholdict16 = {'supermarkt': "Albert Heijn", 'wat': "Wieckse, Amstel en Bavaria 0.0", 'korting': "25 procent" , 'hoeveel': "6 blikjes a 0.33 liter", 'normaal': "2 euro en 62 cent", 'deze week': "1 euro en 96 cent"}
Alcoholdict17 = {'supermarkt': "Albert Heijn", 'wat': "Heineken pils", 'korting': "25 procent" , 'hoeveel': "6 blikjes a 0.33 liter", 'normaal': "5 euro en 79 cent", 'deze week': "4 euro en 34 cent"}
Alcoholdict18 = {'supermarkt': "Plus", 'wat': "Grolsch pils", 'korting': "5 euro en 70 cent" , 'hoeveel': "krat 24 flesjes", 'normaal': "14 euro en 69 cent", 'deze week': "8 euro en 99 cent"}
Alcoholdict19 = {'supermarkt': "Plus", 'wat': "Jupiler pils", 'korting': "5 euro en 20 cent" , 'hoeveel': "krat 24 flesjes a 25 cl", 'normaal': "14 euro en 19 cent", 'deze week': "8 euro en 99 cent"}
Alcoholdict20 = {'supermarkt': "Plus", 'wat': "Desperados", 'korting': "1 euro en 40 cent" , 'hoeveel': "set 6 flesjes a 33 cl", 'normaal': "4 euro en 89 cent", 'deze week': "3 euro en 49 cent"}
Alcoholdict21 = {'supermarkt': "Plus", 'wat': "mousserende wijn", 'korting': "25 procent" , 'hoeveel': "flessen a 75 cl", 'normaal': "4 euro en 49 cent", 'deze week': "3 euro en 36 cent"}
Alcoholdict22 = {'supermarkt': "Lidl", 'wat': "Conte de brismand champange brut", 'korting': "3 euro" , 'hoeveel': "per fles", 'normaal': "12 euro en 99 cent", 'deze week': "9 euro en 99 cent"}
Alcoholdict23 = {'supermarkt': "Lidl", 'wat': "champange brut brissinger", 'korting': "1 euro" , 'hoeveel': "per fles", 'normaal': "15 euro en 99 cent", 'deze week': "14 euro en 99 cent"}
Alcoholdict24 = {'supermarkt': "Lidl", 'wat': "Oettinger pils", 'korting': "2 euro en 98 cent" , 'hoeveel': "2 kratten", 'normaal': "14 euro en 98 cent", 'deze week': "12 euro"}
