Belegdict = {'supermarkt': "Spar", 'wat': "Runderrookvlees", 'korting': "40 cent" , 'hoeveel': "100 gram", 'normaal': "2 euro en 49 cent", 'deze week': "1 euro en 99 cent"}
Belegdict1 = {'supermarkt': "Spar", 'wat': "Sparwoude kaasplakken", 'korting': "25 procent" , 'hoeveel': "200 gram", 'normaal': "2 euro en 79 cent", 'deze week': "2 euro en 9 cent"}
Belegdict2 = {'supermarkt': "Spar", 'wat': "Kipfilet", 'korting': "60 cent" , 'hoeveel': "100 gram", 'normaal': "1 euro en 99 cent", 'deze week': "1 euro en 39 cent"}
Belegdict3 = {'supermarkt': "Jumbo", 'wat': "Jong of jong belegen kaas", 'korting': "2 euro en 89 cent" , 'hoeveel': "1 kilo", 'normaal': "8 euro en 89 cent", 'deze week': "6 euro"}
Belegdict4 = {'supermarkt': "Jan Linders", 'wat': "Castello creamy blue", 'korting': "20 cent" , 'hoeveel': "150 gram", 'normaal': "1 euro en 89 cent", 'deze week': "1 euro en 69 cent"}
Belegdict5 = {'supermarkt': "Jan Linders", 'wat': "Kaas 48+", 'korting': "96 cent" , 'hoeveel': "500 gram", 'normaal': "3 euro en 95 cent", 'deze week': "2 euro en 99 cent"}
Belegdict6 = {'supermarkt': "Jan Linders", 'wat': "Licht gerookte kipfilet", 'korting': "40 cent" , 'hoeveel': "100 gram", 'normaal': "2 euro en 19 cent", 'deze week': "1 euro en 79 cent"}
Belegdict7 = {'supermarkt': "Jan Linders", 'wat': "Ambachtelijke achterham", 'korting': "80 cent" , 'hoeveel': "100 gram", 'normaal': "2 euro en 49 cent", 'deze week': "1 euro en 69 cent"}
Belegdict8 = {'supermarkt': "Jan Linders", 'wat': "Old amsterdam kaas", 'korting': "25 procent" , 'hoeveel': "125 gram", 'normaal': "1 euro en 89 cent", 'deze week': "1 euro en 42 cent"}
Belegdict9 = {'supermarkt': "Jan Linders", 'wat': "Milner kaasplakken", 'korting': "1+1 gratis" , 'hoeveel': "175 gram", 'normaal': "4 euro en 90 cent", 'deze week': "2 euro en 45 cent"}
Belegdict10 = {'supermarkt': "Albert Heijn", 'wat': "Pate", 'korting': "28 cent" , 'hoeveel': "100 gram", 'normaal': "1 euro en 14 cent", 'deze week': "86 cent"}
Belegdict11 = {'supermarkt': "Albert Heijn", 'wat': "Buitenlandse kaasjes", 'korting': "25 procent" , 'hoeveel': "100 gram", 'normaal': "1 euro en 20 cent", 'deze week': "90 cent"}
Belegdict12 = {'supermarkt': "Albert Heijn", 'wat': "Goudse kaas", 'korting': "25 procent" , 'hoeveel': "250 gram", 'normaal': "2 euro en 81 cent", 'deze week': "2 euro en 11 cent"}
Belegdict13 = {'supermarkt': "Albert Heijn", 'wat': "Hero jam", 'korting': "25 procent" , 'hoeveel': "340 gram", 'normaal': "2 euro en 85 cent", 'deze week': "1 euro en 37 cent"}
Belegdict14 = {'supermarkt': "Plus", 'wat': "filet americain", 'korting': "36 cent" , 'hoeveel': "bakje 150 gram", 'normaal': "2 euro en 25 cent", 'deze week': "1 euro en 89 cent"}
Belegdict15 = {'supermarkt': "Plus", 'wat': "Runderrookvlees", 'korting': "41 cent" , 'hoeveel': "100 gram", 'normaal': "2 euro en 70 cent", 'deze week': "2 euro en 29 cent"}
Belegdict16 = {'supermarkt': "Plus", 'wat': "Moment pate", 'korting': "40 cent" , 'hoeveel': "150 gram", 'normaal': "1 euro en 59 cent", 'deze week': "1 euro en 19 cent"}
Belegdict17 = {'supermarkt': "Plus", 'wat': "Klaverland kaas", 'korting': "1 euro en 64 cent" , 'hoeveel': "500 gram", 'normaal': "5 euro en 63 cent", 'deze week': "3 euro en 99 cent"}
