Fruitdict = {'supermarkt': "Spar", 'wat': "2 netten perssinaasappelen", 'korting': "1+1 gratis", 'hoeveel': "2 kilo", 'normaal': "5 euro en 98 cent", 'deze week': "2 euro en 99 cent"}
Fruitdict1 = {'supermarkt': "Jan Linders", 'wat': "Goudreinette appels", 'korting': "80 cent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 69 cent", 'deze week': "79 cent"}
Fruitdict2 = {'supermarkt': "Jan Linders", 'wat': "pitloze witte druiven", 'korting': "60 cent" , 'hoeveel': "bak 500 gram", 'normaal': "2 euro en 69 cent", 'deze week': "1 euro en 99 cent"}
Fruitdict3 = {'supermarkt': "Jan Linders", 'wat': "Mango", 'korting': "60 cent" , 'hoeveel': "1 stuk", 'normaal': "1 euro en 69 cent", 'deze week': "99 cent"}
Fruitdict4 = {'supermarkt': "Jan Linders", 'wat': "Handdinaasappels los", 'korting': "50 procent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 99 cent", 'deze week': "99 cent"}
Fruitdict5 = {'supermarkt': "Albert Heijn", 'wat': "Rode Goudreinette", 'korting': "40 procent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 49 cent", 'deze week': "89 cent"}
Fruitdict6 = {'supermarkt': "Albert Heijn", 'wat': "Fruitpunch", 'korting': "50 cent" , 'hoeveel': "600 gram", 'normaal': "4 euro", 'deze week': "3 euro en 50 cent"}
Fruitdict7 = {'supermarkt': "Albert Heijn", 'wat': "Elstar", 'korting': "40 procent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 39 cent", 'deze week': "83 cent"}
Fruitdict8 = {'supermarkt': "Plus", 'wat': "Kiwi", 'korting': "79 cent" , 'hoeveel': "500 gram", 'normaal': "1 euro en 79 cent", 'deze week': "1 euro"}
Fruitdict9 = {'supermarkt': "Plus", 'wat': "Perssinaasappelen", 'korting': "80 cent" , 'hoeveel': "2 kilo", 'normaal': "2 euro en 79 cent", 'deze week': "1 euro en 99 cent"}
Fruitdict10 = {'supermarkt': "Plus", 'wat': "Goudreinette", 'korting': "1 euro en 40 cent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 89 cent", 'deze week': "49 cent"}
Fruitdict11 = {'supermarkt': "Plus", 'wat': "Kaki", 'korting': "1 euro en 10 cent" , 'hoeveel': "1 kilo", 'normaal': "2 euro en 49 cent", 'deze week': "1 euro en 39 cent"}
Fruitdict12 = {'supermarkt': "Plus", 'wat': "Granaatappel", 'korting': "70 cent" , 'hoeveel': "per stuk", 'normaal': "1 euro en 60 cent", 'deze week': "99 cent"}
Fruitdict13 = {'supermarkt': "Plus", 'wat': "pitloze witte druiven", 'korting': "1 euro en 30 cent" , 'hoeveel': "500 gram", 'normaal': "2 euro en 69 cent", 'deze week': "1 euro en 39 cent"}