Groentedict = {'supermarkt': "Spar", 'wat': "1 zak Hutspot", 'korting': "39 procent", 'hoeveel': "500 gram", 'normaal': "1 euro en 19 cent", 'deze week':"59 cent"}
Groentedict1 = {'supermarkt': "Spar", 'wat': "Slamelange", 'korting': "1 euro 20 cent" , 'hoeveel': "200 gram", 'normaal': "2 euro en 59 cent", 'deze week': "1 euro en 39 cent"}
Groentedict2 = {'supermarkt': "Spar", 'wat': "Zongedroogde tomaatjes", 'korting': "50 cent" , 'hoeveel': "270 gram", 'normaal': "2 euro en 24 cent", 'deze week': "1 euro en 69 cent"}
Groentedict3 = {'supermarkt': "Spar", 'wat': "Olijven groen", 'korting': "20 cent" , 'hoeveel': "240 ml", 'normaal': "69 cent", 'deze week': "49 cent"}
Groentedict4 = {'supermarkt': "Spar", 'wat': "Komkommer", 'korting': "1+1 gratis" , 'hoeveel': "2 stuks", 'normaal': "1 euro en 79 cent", 'deze week': "89 cent"}
Groentedict5 = {'supermarkt': "Spar", 'wat': "Bonduelle", 'korting': "48 cent" , 'hoeveel': "300 gram", 'normaal': "1 euro en 37 cent", 'deze week': "79 cent"}
Groentedict6 = {'supermarkt': "Jumbo", 'wat': "Hak appelmoes of groenteconserven", 'korting': "1 euro en 45 cent" , 'hoeveel': "5 potten a 370 ml", 'normaal': "4 euro en 95 cent", 'deze week': "3 euro en 50 cent"}
Groentedict7 = {'supermarkt': "Jan Linders", 'wat': "Boerenkool fijn", 'korting': "40 cent" , 'hoeveel': "500 gram", 'normaal': "1 euro en 89 cent", 'deze week': "1 euro en 49 cent"}
Groentedict8 = {'supermarkt': "Jan Linders", 'wat': "Zoete puntpaprika", 'korting': "40 cent" , 'hoeveel': "500 gram", 'normaal': "1 euro en 49 cent", 'deze week': "99 cent"}
Groentedict9 = {'supermarkt': "Jan Linders", 'wat': "Sperziebonen los", 'korting': "10 cent" , 'hoeveel': "500 gram", 'normaal': "1 euro en 59 cent", 'deze week': "1 euro en 49 cent"}
Groentedict10 = {'supermarkt': "Albert Heijn", 'wat': "Rode paprika", 'korting': "51 cent" , 'hoeveel': "2 stuks", 'normaal': "1 euro en 30 cent", 'deze week': "79 cent"}
Groentedict11 = {'supermarkt': "Albert Heijn", 'wat': "Wokgroente", 'korting': "1 euro en 95 cent" , 'hoeveel': "2 zakken 400 gram", 'normaal': "4 euro en 95 cent", 'deze week': "3 euro"}
Groentedict12 = {'supermarkt': "Plus", 'wat': "Groente pakket", 'korting': "30 cent" , 'hoeveel': "500 gram", 'normaal': "1 euro en 59 cent", 'deze week': "1 euro en 29 cent"}
Groentedict13 = {'supermarkt': "Plus", 'wat': "Komkommer", 'korting': "51 cent" , 'hoeveel': "2 stuks", 'normaal': "1 euro en 50 cent", 'deze week': "99 cent"}
Groentedict14 = {'supermarkt': "Plus", 'wat': "paprika mix", 'korting': "6 cent" , 'hoeveel': "3 stuks", 'normaal': "1 euro en 5 cent", 'deze week': "99 cent"}
Groentedict15 = {'supermarkt': "Plus", 'wat': "Spitskool", 'korting': "20 cent" , 'hoeveel': "per stuk", 'normaal': "1 euro en 9 cent", 'deze week': "89 cent"}
Groentedict16 = {'supermarkt': "Lidl", 'wat': "Goudreinette", 'korting': "60 cent" , 'hoeveel': "per kilo", 'normaal': "1 euro en 29 cent", 'deze week': "69 cent"}